* Code Documentation
This README contains documentation on the code used in my MSc Thesis project.
- all code packaged as a pip package split into two main sub modules relating to specific functionality
  + Dataset synthesis
  + General utility (plots paths)

* Table of Contents :TOC_1:
- [[#code-documentation][Code Documentation]]
- [[#install-guide][Install Guide]]
- [[#dependencies][Dependencies]]
- [[#quick-start-guide][Quick-start Guide]]

* Install Guide
If you only wish to use the package:
#+begin_src shell
pip install git+https://github.com/BenjaminFrazer/nilmtk/@benDevel
pip install git+https://github.com/BenjaminFrazer/thesis_tools
#+end_src

Alternatively if you wish to edit and/or inspect a local copy of the package:
#+begin_src shell
pip install git+https://github.com/BenjaminFrazer/nilmtk/@benDevel
git clone -e https://github.com/BenjaminFrazer/thesis_tools <yourDesiredPath>
cd <yourDesiredPath>
pip install -e .
#+end_src

The contrib package may be installed using the following command when using bash:
#+begin_src shell
pip install -e git+https://github.com/nilmtk/nilmtk-contrib#egg=nilmtk-contrib
#+end_src

Or with zsh (hash is a special character that must be escaped with zsh):
#+begin_src shell
pip install -e git+https://github.com/nilmtk/nilmtk-contrib'#'egg=nilmtk-contrib
#+end_src

It should be noted that I faced difficulty getting NILMTK-contrib working with pip due to broken package dependencies. This can be worked around to get some of the algorithms working by editing the package source as detailed in [[file:../guides/nilmtk_install_guide.org][this guide]].

* Dependencies
| Name                   | Version |
|------------------------+---------|
| Python                 |     3.8 |
| Pandas                 |  0.25.3 |
| Numpy                  |  1.19.3 |
| [[https://github.com/BenjaminFrazer/nilmtk.git][BenjaminFrazer/NILMTK]]* |   0.4.3 |
| [[https://github.com/nilmtk/nilmtk-contrib][NILMTK-contrib]]**       |   0.1.2 |
| [[https://github.com/nilmtk/nilm_metadata/][NILM-Metadata]]          |   0.2.4 |

*Notes:*

*The author's fork of the NILMTK is used in this work which includes several improvements in the way in which the experimentation API records result. These changes were necessitated by the large number of data-points generated by the parameter sweeps used in this work. These changes are non breaking and have been build with reintegration into NILMTK in mind. Full documentation of these changes can be found in the repository itself.

**Optional: Only required for advanced NILM algorithms.

* TODO Quick-start Guide
** TODO Dataset Generation
** TODO Running NILM Experiments & Test sweeps
** TODO Plotting Results
